name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '33 0,3,6,9,12,15,18,21 * * *' # once every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for update site changes
        run: |
          # CTR START HERE - This is wrong.
          # Think carefully about how to generate dates.txt
          # for *the most recent Fiji bundle*, not for
          # *the most recent update site changes*.
          # Could we use Last-Modified of downloads.imagej.net/fiji/latest ?
          ./fetch-datestamps.sh > dates.txt

      - name: Preconfigure the cache
        run: |
          mkdir -p ~/cache

      - name: Print variables before
        run: ./print-vars.sh

      - name: Configure the cache
        uses: actions/cache@v2
        with:
          path: ~/cache
          key: ${{ runner.os }}-${{ hashFiles('dates.txt') }}

      - name: Print variables after
        run: ./print-vars.sh

      - name: Execute the build
        run: ./build.sh
        env:
           WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
           WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
